### ISSUE TITLE
make sure issued certificate does not outlive CA

### ISSUE THREAD

**Issue by ghost** [letsconnectvpn/vpn-ca#6]

**Comment by ghost** [comment]
maybe we can automate this? in case the `-not-after` is > liftetime of CA we can "cap" it at the `-not-after` of the CA?

**Comment by jornane** [comment]
Rather throw an exception, don't do something else than the user asked for.

**Comment by ghost** [comment]
Yes that is a very good point. I was before thinking of logging a warning, but well, maybe I should just error out.

**Comment by ghost** [comment]
Done.
